//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: non-nrs
//* =======================================

import {
  createOptionList,
  nonNRSCategories,
  nonNRSGoals,
  nonNRSSites
} from "../main.js";

export const createNonNRSContent = (list) => {
  const tableBodyContent = [];
  const orderedList = list.sort(
    (item1, item2) =>
      Number(item2.FY) - Number(item1.FY) ||
      Number(item1.Category_Key) - Number(item2.Category_Key)
  );
  console.log("orderedList Non NRS:>> ", orderedList);
  for (const record of orderedList) {
    const { ID, Category_Key, GoalID, FY, MetGoal, ReferralSiteID } = record;
    const yesNoList = [
      { key: "0", value: "No" },
      { key: "1", value: "Yes" }
    ];
    const optionListCategory = createOptionList(nonNRSCategories, Category_Key);
    const optionListGoal = createOptionList(nonNRSGoals, GoalID);
    const optionListSites = createOptionList(nonNRSSites, ReferralSiteID);
    const optionListGoalMet = createOptionList(yesNoList, MetGoal);

    const row = `
    <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip" data-placement="left">
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="FY" value=${FY}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="Category_Key">
            ${optionListCategory}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="GoalID">
            ${optionListGoal}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="MetGoal">
            ${optionListGoalMet}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="ReferralSiteID">
            <option></option>
            ${optionListSites}
          </select>
        </div>
      </td>
    </tr>
    `;
    tableBodyContent.push(row);
  }
  return tableBodyContent.join("");
};

export const addNewNonNRSGoals = (obj) => {
  const content = [];
  const { labels } = obj;
  let labelClassVal = "";
  let classVal = "";
  for (const keyValue in labels) {
    const labelVal = labels[keyValue];
    let row = "";
    let option = "";
    let value = "";
    // <input> fields
    if (["FY"].includes(keyValue)) {
      let optionHidden = "form-group";
      // elementInput() ==> helpers/helperFunctions.js
      row = elementInput({
        keyVal: keyValue,
        labelVal,
        value,
        labelClassVal,
        classVal,
        option,
        optionHidden,
        type: "text"
      });
    } else {
      // <select> fields
      let hashTable;
      switch (keyValue) {
        case "Category_Key":
          hashTable = nonNRSCategories;
          break;
        case "GoalID":
          hashTable = nonNRSGoals;
          break;
        case "MetGoal":
          hashTable = [
            { key: "0", value: "No" },
            { key: "1", value: "Yes" }
          ];
          break;
        case "ReferralSiteID":
          hashTable = nonNRSSites;
          break;
        default:
          console.log("Default hit - Not right");
          return;
      }
      // elementSelectModal() ==> helpers/helperFunction.js
      row = elementSelectModal({
        hashTable,
        keyValue,
        selectedValue: "",
        labelVal,
        labelClassVal,
        option,
        optionText: ""
      });
    }
    content.push(row);
  }
  return content.join("");
};
