//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: other
//* =======================================

import { createOptionList, otherGoalsList } from "../main.js";

export const createOtherContent = (list) => {
  const tableBodyContent = [];
  const orderedList = list.sort((item1, item2) =>
    item1.GoalID < item2.GoalID ? -1 : item1.GoalID > item2.GoalID ? 1 : 0
  );

  for (const record of orderedList) {
    const { ID, GoalID, SetGoal, ShowProgress, ShowProficiency } = record;

    const optionListGoal = createOptionList(otherGoalsList, GoalID);
    const yesNoList = [
      { key: "", value: "No" },
      { key: "checked", value: "Yes" }
    ];
    const optionListSetGoal = createOptionList(yesNoList, SetGoal);
    const optionListProgress = createOptionList(yesNoList, ShowProgress);
    const optionListProficiency = createOptionList(yesNoList, ShowProficiency);

    const row = `
    <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip" data-placement="left">
    <td>
      <div class="form-group input-field">
        <select class="modal-select" disabled name="OutComeID">
          ${optionListOutcome}
        </select>
      </div>
    </td>
    </tr>

    `;
  }
  return tableBodyContent.join("");
};
