//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: other
//* =======================================

import { createOptionList, otherGoalsList } from "../main.js";

export const createOtherContent = (list) => {
  const tableBodyContent = [];
  const orderedList = list.sort((item1, item2) =>
    item1.GoalID < item2.GoalID ? -1 : item1.GoalID > item2.GoalID ? 1 : 0
  );
  for (const record of orderedList) {
    const { ID, GoalID, SetGoal, ShowProgress, ShowProficiency } = record;

    const optionListGoal = createOptionList(otherGoalsList, GoalID);
    const yesNoList = [
      { key: "0", value: "No" },
      { key: "1", value: "Yes" }
    ];
    const optionListSetGoal = createOptionList(yesNoList, SetGoal);
    const optionListProgress = createOptionList(yesNoList, ShowProgress);
    const optionListProficiency = createOptionList(yesNoList, ShowProficiency);
    const row = `
    <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip" data-placement="left">
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="GoalID">
            ${optionListGoal}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="SetGoal">
            ${optionListSetGoal}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="ShowProgress">
            ${optionListProgress}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="ShowProficiency">
            ${optionListProficiency}
          </select>
        </div>
      </td>
    </tr>
    `;
    tableBodyContent.push(row);
  }
  return tableBodyContent.join("");
};

export const addNewOutcomeOther = (obj) => {
  const content = [];
  const { labels } = obj;
  let labelClassVal = "";

  for (const keyValue in labels) {
    const labelVal = labels[keyValue];
    let row = "";
    let option = "";

    // <select> fields
    let hashTable;
    switch (keyValue) {
      case "GoalID":
        hashTable = otherGoalsList;
        break;
      default:
        hashTable = [
          { key: "0", value: "No" },
          { key: "1", value: "Yes" }
        ];
    }
    // elementSelectModal() ==> helpers/helperFunction.js
    row = elementSelectModal({
      hashTable,
      keyValue,
      selectedValue: "",
      labelVal,
      labelClassVal,
      option,
      optionText: ""
    });
    content.push(row);
  }
  return content.join("");
};
