//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: wioa
//* =======================================
const labels = {
  OutcomeID: "Status",
  OutcomeFY: "Fiscal year",
  Quarter: "Quarter",
  SurveyDate: "Survey date",
  OutcomeDate: "Outcome date",
  Income: "Quarterly income",
  NYSED_CredentialID: "Credential"
};
export const createWioaContent = (list, outcomes, credentials) => {
  const content = [];
  const orderedList = list.sort(
    (record1, record2) => Number(record1.OutcomeFY) > Number(record2.OutcomeFY)
  );
  const fieldList = Object.keys(labels);
  for (const record of orderedList) {
    let { ID } = record;
    const row = fieldList
      .map((field) => {
        let val = "";
        switch (field) {
          case "OutcomeID":
            val = outcomes.find((item) => item.key === record[field]).value;
            break;
          case "NYSED_CredentialID":
            val = record[field]
              ? credentials.find((item) => item.key === record[field]).value
              : "";
            break;

          default:
            val = record[field];
            break;
        }
        return `<td>${val}</td>`;
      })
      .join("");
    content.push(`<tr id=${ID}>${row}</tr>`);
  }
  return content.join("");
};
