        const partnersData = [
                { "ID": "2828", "AgencyID": "PRA", "ReferralSiteID": "PRALZ2828", "ReferralSiteName": "ASISTS Data Services", "ReferralSiteManager": "Gregory Jacques", "Address": "455 5th Avenue", "City": "New York", "State": "", "Zip": "10016", "County": "", "CountyDesc": "", "Telephone": "(212) 555-5005", "ReferralSiteEmail": "gjdeve@lacnyc.org" },
                { "ID": "3370", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3370", "ReferralSiteName": "ASISTS Release_12.4", "ReferralSiteManager": "LAC", "Address": "85 Broad Street", "City": "New York", "State": "NY", "Zip": "10000-4004", "County": "", "CountyDesc": "", "Telephone": "", "ReferralSiteEmail": "katet@lacnyc.org" },
                { "ID": "3082", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3082", "ReferralSiteName": "ASISTS Test 12.0 Site 2", "ReferralSiteManager": "Raju Srinivasan", "Address": "85 Broad Street", "City": "New York", "State": "", "Zip": "10014-____", "County": "", "CountyDesc": "", "Telephone": "(212) 803-3355", "ReferralSiteEmail": "test" },
                { "ID": "3105", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3105", "ReferralSiteName": "ASISTS Test 12.1_Build 2", "ReferralSiteManager": "Raju Srinivasan", "Address": "85 Broad Street", "City": "New York", "State": "NY", "Zip": "10004-____", "County": "36061", "CountyDesc": "36061 NY County (Manhattan)", "Telephone": "(212) 803-3355", "ReferralSiteEmail": "" },
                { "ID": "3334", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3334", "ReferralSiteName": "ASISTS_Release 12.3", "ReferralSiteManager": "Literacy Assistance Center ", "Address": "85 Broad Street ", "City": "New York ", "State": "NY", "Zip": "10004-____", "County": "", "CountyDesc": "", "Telephone": "(212) 803-3000", "ReferralSiteEmail": "" },
                { "ID": "3374", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3374", "ReferralSiteName": "ASPCA", "ReferralSiteManager": "", "Address": "", "City": "", "State": "", "Zip": "_____-____", "County": "", "CountyDesc": "", "Telephone": "(___) ___-____", "ReferralSiteEmail": "ASPCAisGreat@email.com" },
                { "ID": "2988", "AgencyID": "PRA", "ReferralSiteID": "PRALZ2988", "ReferralSiteName": "Beta Build 11.1-0 RS", "ReferralSiteManager": "Raju Srinivasan", "Address": "85 Broad Street", "City": "New York", "State": "NY", "Zip": "10004-____", "County": "", "CountyDesc": "", "Telephone": "(212) 555-5316", "ReferralSiteEmail": "" },
                { "ID": "3009", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3009", "ReferralSiteName": "Beta Build 11.2- RS", "ReferralSiteManager": "Raju Srinivasan", "Address": "85 Broad Street ", "City": "New York ", "State": "NY", "Zip": "10004-____", "County": "", "CountyDesc": "", "Telephone": "(212) 803-3355", "ReferralSiteEmail": "" },
                { "ID": "3016", "AgencyID": "PRA", "ReferralSiteID": "PRALZ3016", "ReferralSiteName": "Beta Build 11.3 RS", "ReferralSiteManager": "Raju Srinivasan", "Address": "85 Broad Street 27th Floor", "City": "New York", "State": "NY", "Zip": "10004-____", "County": "36061", "CountyDesc": "36061 NY County(Manhattan)", "Telephone": "(212) 555-3321", "ReferralSiteEmail": "" },
                { "ID": "2678", "AgencyID": "PRA", "ReferralSiteID": "PRALZ2678", "ReferralSiteName": "Buffalo ARC", "ReferralSiteManager": "", "Address": "", "City": "", "State": "", "Zip": "", "County": "", "CountyDesc": "", "Telephone": "(___) ___-____", "ReferralSiteEmail": "" }
        ];

        const countyData = [
                    { "FIPS": "36001", "CountyDesc": "36001 Albany" },
                    { "FIPS": "36003", "CountyDesc": "36003 Allegany" },
                        {"FIPS": "36061", "CountyDesc": "36061 NY County (Manhattan)"},
 { "FIPS": "36007", "CountyDesc": "36007 Broome" },
                    { "FIPS": "36005", "CountyDesc": "36005 Bronx" },
                    { "FIPS": "36009", "CountyDesc": "36009 Cattaraugus" },
                    { "FIPS": "36021", "CountyDesc": "36021 Columbia" },
                    { "FIPS": "36015", "CountyDesc": "36015 Chemung" },
                    { "FIPS": "36019", "CountyDesc": "36019 Clinton" },
                    { "FIPS": "36017", "CountyDesc": "36017 Chenango" },
                    { "FIPS": "36013", "CountyDesc": "36013 Chautauqua" }
        ];
        const sessionVariable = {
                AgencyID: "PRA",
                AuditUserID: '<%= Session["UserID"] %>',
                FiscalYear: ["2016", "2017"],
                };
                
            const ddlStates = [
                { objKey: "AL", objValue: "Alabama" },
                { objKey: "AS", objValue: "American Samoa" },
                { objKey: "AK", objValue: "Alaska" },
                { objKey: "AZ", objValue: "Arizona" },
                { objKey: "AR", objValue: "Arkansas" },
                { objKey: "CA", objValue: "California" },
                { objKey: "CO", objValue: "Colorado" },
                { objKey: "CT", objValue: "Connecticut" },
                { objKey: "DE", objValue: "Delaware" },
                { objKey: "DC", objValue: "District Of Columbia" },
                { objKey: "FM", objValue: "Federated States Of Micronesia" },
                { objKey: "FL", objValue: "Florida" },
                { objKey: "GA", objValue: "Georgia" },
                { objKey: "GU", objValue: "Guam" },
                { objKey: "HI", objValue: "Hawaii" },
                { objKey: "ID", objValue: "Idaho" },
                { objKey: "IL", objValue: "Illinois" },
                { objKey: "IN", objValue: "Indiana" },
                { objKey: "IA", objValue: "Iowa" },
                { objKey: "KS", objValue: "Kansas" },
                { objKey: "KY", objValue: "Kentucky" },
                { objKey: "LA", objValue: "Louisiana" },
                { objKey: "ME", objValue: "Maine" },
                { objKey: "MH", objValue: "Marshall Islands" },
                { objKey: "MD", objValue: "Maryland" },
                { objKey: "MA", objValue: "Massachusetts" },
                { objKey: "MI", objValue: "Michigan" },
                { objKey: "MN", objValue: "Minnesota" },
                { objKey: "MS", objValue: "Mississippi" },
                { objKey: "MO", objValue: "Missouri" },
                { objKey: "MT", objValue: "Montana" },
                { objKey: "NE", objValue: "Nebraska" },
                { objKey: "NV", objValue: "Nevada" },
                { objKey: "NH", objValue: "New Hampshire" },
                { objKey: "NJ", objValue: "New Jersey" },
                { objKey: "NM", objValue: "New Mexico" },
                { objKey: "NY", objValue: "New York" },
                { objKey: "NC", objValue: "North Carolina" },
                { objKey: "ND", objValue: "North Dakota" },
                { objKey: "MP", objValue: "Northern Mariana Islands" },
                { objKey: "OH", objValue: "Ohio" },
                { objKey: "OK", objValue: "Oklahoma" },
                { objKey: "OR", objValue: "Oregon" },
                { objKey: "PW", objValue: "Palau" },
                { objKey: "PA", objValue: "Pennsylvania" },
                { objKey: "PR", objValue: "Puerto Rico" },
                { objKey: "RI", objValue: "Rhode Island" },
                { objKey: "SC", objValue: "South Carolina" },
                { objKey: "SD", objValue: "South Dakota" },
                { objKey: "TN", objValue: "Tennessee" },
                { objKey: "TX", objValue: "Texas" },
                { objKey: "UT", objValue: "Utah" },
                { objKey: "VT", objValue: "Vermont" },
                { objKey: "VI", objValue: "Virgin Islands" },
                { objKey: "VA", objValue: "Virginia" },
                { objKey: "WA", objValue: "Washington" },
                { objKey: "WV", objValue: "West Virginia" },
                { objKey: "WI", objValue: "Wisconsin" },
                { objKey: "WY", objValue: "Wyoming" },
                  ];