//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: CTED
//* =======================================

import { createOptionList } from "../main.js";
import { enrollValues } from "./enrollment.js";

// Populating input element values
// Data source: /data-server.js/GetCTED
//            /data-server.js/GetCTEDSource

export const ctedValues = (list, sourceList) => {
  const tableBodyContent = [];
  const FYList = [];
  const actualFY = Number(createCredentials().FiscalYear);
  for (let i = actualFY; i > actualFY - 20; i--) {
    FYList.push({ key: i.toString(), value: i.toString() });
  }
  const enrollStatus = [
    { key: "1", value: "Left CTEDS" },
    { key: "2", value: "Completed" },
    { key: "3", value: "Continuing" }
  ];
  const studentStatus = [
    { key: "1", value: "Related Employment" },
    { key: "2", value: "Unrelated Employment" },
    { key: "3", value: "The Military" },
    { key: "4", value: "Other Education" },
    { key: "5", value: "Unemployed" },
    { key: "6", value: "Not in Labor Force" },
    { key: "7", value: "Status Unknown" }
  ];
  // console.log("FYList :>> ", FYList);
  for (const record of list) {
    const {
      ID,
      CTEDPrimaryProg,
      CTDEFY,
      CTEDEnrollmentStatus,
      CTEDStudentStatus
    } = record;
    const optionListFY = createOptionList(FYList, CTDEFY);
    const optionListEnrollStatus = createOptionList(
      enrollStatus,
      CTEDEnrollmentStatus
    );
    const optionListStudentStatus = createOptionList(
      studentStatus,
      CTEDStudentStatus
    );
    const optionListPrograms = createOptionList(sourceList, CTEDPrimaryProg);
    const row = `
    <tr id="${ID}">
    <td>
    <div class="form-field input-group">
    <select disabled class="modal-select" name="CTEDPrimaryProg" >
    ${optionListPrograms}
  </select>
    </div>
    </td>
    <td>
    <div class="form-field input-group">
    <select disabled class="modal-select" name="CTDEFY" >
    ${optionListFY}
  </select>
    </div>
    </td>
    <td>
    <div class="form-field input-group">
    <select disabled class="modal-select" name="CTEDEnrollmentStatus" >
    ${optionListEnrollStatus}
  </select>
    </div>
    </td>
    <td>
    <div class="form-field input-group">
    <select disabled class="modal-select" name="CTEDStudentStatus" >
    ${optionListStudentStatus}
  </select>
    </div>
    </td>
    </tr>`;

    tableBodyContent.push(row);
  }

  $(".cted-form tbody").append(tableBodyContent.join(""));
};
