//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Contact hours summary, Contact hours history
//* =======================================

import { createOptionList } from "../main.js";

// Populating input element values
// Data source: /data-server.js/GetHours
//          /data-server.js/GetInstructionSource
export const hourSummaryValues = (list, codeList) => {};
