//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Notes
//* =======================================
