const ielcePartnersData = [
{"ID":"10","AgencyID":"PRA","IELCEPartnerID":"PRAIELCE10","PartnerName":"IEL-12.3","PartnerManager":"ASISTS Data Services ","Address":"85 Broad Street ","City":"New York ","State":"NY","Zip":"10004-____","County":"","Telephone":"","PartnerFSID":"EPE","AmountProj":"70000.00","AmountAct":"70000.00","PartnerTrainingType":"Workforce Readiness","PartnerCredential":"Certification","CountyDesc":"","PartnerFSIDDesc":"EPE"},{"ID":"2","AgencyID":"PRA","IELCEPartnerID":"PRAIELCE2","PartnerName":"IEL-4","PartnerManager":"Raj Srinivasan","Address":"85 Broad Street","City":"New York","State":"NY","Zip":"10004-____","County":"36061","Telephone":"(212) 555-1000","PartnerFSID":"EPE","AmountProj":"80.00","AmountAct":"80.00","PartnerTrainingType":"","PartnerCredential":"Workforce Certification","CountyDesc":"36061 NY County(Manhattan)","PartnerFSIDDesc":"EPE"},{"ID":"8","AgencyID":"PRA","IELCEPartnerID":"PRAIELCE8","PartnerName":"IEL-5","PartnerManager":"LAC ","Address":"85 Broad Street 27th floor ","City":"New York ","State":"NY","Zip":"10004-0000","County":"","Telephone":"","PartnerFSID":"EPE","AmountProj":"50000.00","AmountAct":"50000.00","PartnerTrainingType":"Workforce","PartnerCredential":"Certificate","CountyDesc":"","PartnerFSIDDesc":"EPE"},{"ID":"1","AgencyID":"PRA","IELCEPartnerID":"PRAIELCE1","PartnerName":"LACnyc","PartnerManager":"Gregory upd","Address":"85 Broad Street","City":"","State":"","Zip":"_____-____","County":"36035","Telephone":"(___) ___-____","PartnerFSID":"T1","AmountProj":"44.00","AmountAct":"44.00","PartnerTrainingType":"aaa","PartnerCredential":"ccc","CountyDesc":"36035 Fulton","PartnerFSIDDesc":"Title I"},{"ID":"3","AgencyID":"PRA","IELCEPartnerID":"PRAIELCE3","PartnerName":"westchester branch","PartnerManager":"Kate Tornese","Address":"","City":"","State":"","Zip":"","County":"","Telephone":"","PartnerFSID":"SCHL","AmountProj":"20000.00","AmountAct":"20000.00","PartnerTrainingType":"","PartnerCredential":"","CountyDesc":"","PartnerFSIDDesc":"Scholarship"}] 


        const countyData = [
                    { "FIPS": "36001", "CountyDesc": "36001 Albany" },
                    { "FIPS": "36003", "CountyDesc": "36003 Allegany" },
                    { "FIPS": "36007", "CountyDesc": "36007 Broome" },
                    { "FIPS": "36005", "CountyDesc": "36005 Bronx" },
                    { "FIPS": "36009", "CountyDesc": "36009 Cattaraugus" },
                    { "FIPS": "36021", "CountyDesc": "36021 Columbia" },
                    { "FIPS": "36015", "CountyDesc": "36015 Chemung" },
                    { "FIPS": "36019", "CountyDesc": "36019 Clinton" },
                    { "FIPS": "36017", "CountyDesc": "36017 Chenango" },
                    { "FIPS": "36013", "CountyDesc": "36013 Chautauqua" },
                    { "FIPS": "36061", "CountyDesc": "36061 NY County (Manhattan)" }, {"FIPS":"36035","CountyDesc":"Fulton"}
        ];
        
        const fundingData = [
          {"FSID":"CCF","FundAbbrev":"Community College FTE"},
          {"FSID":"EMP","FundAbbrev":"Employer"},
          {"FSID":"EPE","FundAbbrev":"EPE"},
          {"FSID":"FND","FundAbbrev":"Foundation"},
          {"FSID":"SCHL","FundAbbrev":"Scholarship"},
          {"FSID":"SLF","FundAbbrev":"Self-Pay"},
          {"FSID":"T1","FundAbbrev":"Title I"},
          {"FSID":"UNI","FundAbbrev":"Union"}
      ];
  
        const sessionVariable = {
                AgencyID: "PRA",
                AuditUserID: '<%= Session["UserID"] %>',
                };
                
            const ddlStates = [
                { "Abbrev": "AL", objValue: "Alabama" },
                { "Abbrev": "AS", objValue: "American Samoa" },
                { "Abbrev": "AK", objValue: "Alaska" },
                { "Abbrev": "AZ", objValue: "Arizona" },
                { "Abbrev": "AR", objValue: "Arkansas" },
                { "Abbrev": "CA", objValue: "California" },
                { "Abbrev": "CO", objValue: "Colorado" },
                { "Abbrev": "CT", objValue: "Connecticut" },
                { "Abbrev": "DE", objValue: "Delaware" },
                { "Abbrev": "DC", objValue: "District Of Columbia" },
                { "Abbrev": "FM", objValue: "Federated States Of Micronesia" },
                { "Abbrev": "FL", objValue: "Florida" },
                { "Abbrev": "GA", objValue: "Georgia" },
                { "Abbrev": "GU", objValue: "Guam" },
                { "Abbrev": "HI", objValue: "Hawaii" },
                { "Abbrev": "ID", objValue: "Idaho" },
                { "Abbrev": "IL", objValue: "Illinois" },
                { "Abbrev": "IN", objValue: "Indiana" },
                { "Abbrev": "IA", objValue: "Iowa" },
                { "Abbrev": "KS", objValue: "Kansas" },
                { "Abbrev": "KY", objValue: "Kentucky" },
                { "Abbrev": "LA", objValue: "Louisiana" },
                { "Abbrev": "ME", objValue: "Maine" },
                { "Abbrev": "MH", objValue: "Marshall Islands" },
                { "Abbrev": "MD", objValue: "Maryland" },
                { "Abbrev": "MA", objValue: "Massachusetts" },
                { "Abbrev": "MI", objValue: "Michigan" },
                { "Abbrev": "MN", objValue: "Minnesota" },
                { "Abbrev": "MS", objValue: "Mississippi" },
                { "Abbrev": "MO", objValue: "Missouri" },
                { "Abbrev": "MT", objValue: "Montana" },
                { "Abbrev": "NE", objValue: "Nebraska" },
                { "Abbrev": "NV", objValue: "Nevada" },
                { "Abbrev": "NH", objValue: "New Hampshire" },
                { "Abbrev": "NJ", objValue: "New Jersey" },
                { "Abbrev": "NM", objValue: "New Mexico" },
                { "Abbrev": "NY", objValue: "New York" },
                { "Abbrev": "NC", objValue: "North Carolina" },
                { "Abbrev": "ND", objValue: "North Dakota" },
                { "Abbrev": "MP", objValue: "Northern Mariana Islands" },
                { "Abbrev": "OH", objValue: "Ohio" },
                { "Abbrev": "OK", objValue: "Oklahoma" },
                { "Abbrev": "OR", objValue: "Oregon" },
                { "Abbrev": "PW", objValue: "Palau" },
                { "Abbrev": "PA", objValue: "Pennsylvania" },
                { "Abbrev": "PR", objValue: "Puerto Rico" },
                { "Abbrev": "RI", objValue: "Rhode Island" },
                { "Abbrev": "SC", objValue: "South Carolina" },
                { "Abbrev": "SD", objValue: "South Dakota" },
                { "Abbrev": "TN", objValue: "Tennessee" },
                { "Abbrev": "TX", objValue: "Texas" },
                { "Abbrev": "UT", objValue: "Utah" },
                { "Abbrev": "VT", objValue: "Vermont" },
                { "Abbrev": "VI", objValue: "Virgin Islands" },
                { "Abbrev": "VA", objValue: "Virginia" },
                { "Abbrev": "WA", objValue: "Washington" },
                { "Abbrev": "WV", objValue: "West Virginia" },
                { "Abbrev": "WI", objValue: "Wisconsin" },
                { "Abbrev": "WY", objValue: "Wyoming" },
                  ];