//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Barriers categories
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data.js/GetStudent
//          /data-server.js/ddlBarriers
export const barriersValues = (obj) => {
  let barriersObj = {};
  const keyList = ddlBarriers.map((record) => record.key);
  const formContent = [];
  for (const field in obj) {
    if (keyList.includes(field) && obj[field] !== "2") {
      barriersObj[field] = obj[field];
    }
  }
  const yesNoNAList = [
    { key: "0", value: "No" },
    { key: "1", value: "Yes" },
    { key: "2", value: "No answer" }
  ];
  let optionList = createOptionList(ddlBarriers);
  let optionListYesNoNA = createOptionList(yesNoNAList, "2");
  if (Object.keys(barriersObj).length) {
    for (const key in barriersObj) {
      const keyValue = barriersObj[key];
      optionList = createOptionList(ddlBarriers, key);
      optionListYesNoNA = createOptionList(yesNoNAList, keyValue);
      const row = `
      <div class="input-field form-group col-sm-8">
        <select class="modal-select" name="barrier" disabled>
        <option value>Select a value</option>
          ${optionList}
        </select>
      </div>
      <div class="input-field form-group col-sm-4">
        <select class="modal-select" name="yes-no" disabled>
              ${optionListYesNoNA}
        </select>
      </div>
    `;
      formContent.push(row);
    }
  } else {
    const row = `
    <div class="input-field form-group col-sm-8">
      <select class="modal-select" name="barrier" disabled>
      <option value>Select a value</option>
        ${optionList}
      </select>
    </div>
    <div class="input-field form-group col-sm-4">
      <select class="modal-select" name="yes-no" disabled>
            ${optionListYesNoNA}
      </select>
    </div>`;
    formContent.push(row);
  }
  $(".barriers-form").append(
    `<div class="row">
      ${formContent.join("")}
    </div>`
  );
};

// List argument is dataSource /data-server.js/ddlBarriers
export const addNewSelect = (list, section) => {
  const selection = $(`#edit-form [name=${section}]`)
    .serializeArray()
    .map((item) => item.value);
  // No barrier has a 0 or 1 value  present in the student data
  // Preventing adding a empty select line in the editing modal.
  if (!selection[0]) return;
  const updatedDdl = list.filter((record) => !selection.includes(record.key));
  // Checks if there is at least 1 value left in the list
  if (updatedDdl.length < 1) return;
  const newOptionList = createOptionList(updatedDdl);
  const newSelectLine = `
    <div class="input-field form-group col-sm-8">
      <select class="modal-select" name=${section}>
        <option value>Select a value</option>
        ${newOptionList}
      </select>
    </div>
    <div class="input-field form-group col-sm-4">
      <select class="modal-select medium-input" name="yes-no">
        <option value="2">No answer</option>
        <option value="0">No</option>
        <option value="1">Yes</option>
      </select>
    </div>
    `;
  $("#edit-form .row").append(newSelectLine);
  $(`#edit-form select[name=${section}]:last-of-type`).focus();
};

// Add all the selected choices with their yes/no answer.
export const sectionProcess = (list) => {
  const fields = $("#edit-form").serializeArray();
  const fieldsObj = {};
  const fieldsList = [];
  const filteredList = fields.filter((obj) => obj.value || obj.value !== "2");
  for (let i = 0; i < filteredList.length; i += 2) {
    const key = filteredList[i].value;
    const val = filteredList[i + 1].value;
    fieldsObj[key] = val;
    fieldsList.push(key);
  }
  list
    .map((obj) => obj.key)
    .filter((item) => !fieldsList.includes(item))
    .forEach((item) => (fieldsObj[item] = "2"));
  return fieldsObj;
};
