//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Population categories
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data-additional.js/GetStudent_Additional
//            /data-server.js/ddlPopulation
export const populationValues = (obj) => {
  let populationObj = {};
  const keyList = ddlPopulation.map((record) => record.key);
  const formContent = [];
  for (const field in obj) {
    if (keyList.includes(field) && obj[field] !== "2") {
      populationObj[field] = obj[field];
    }
  }
  const yesNoNAList = [
    { key: "0", value: "No" },
    { key: "1", value: "Yes" },
    { key: "2", value: "No-answer" }
  ];
  let optionList = createOptionList(ddlPopulation);
  let optionListYesNoNA = createOptionList(yesNoNAList, "2");
  if (Object.keys(populationObj).length) {
    for (const key in populationObj) {
      const keyValue = populationObj[key];
      optionList = createOptionList(ddlPopulation, key);
      optionListYesNoNA = createOptionList(yesNoNAList, keyValue);
      const row = `
      <div class="input-field form-group col-sm-8">
        <select class="modal-select" name="population" disabled>
        <option value>Select a value</option>
          ${optionList}
        </select>
      </div>
      <div class="input-field form-group col-sm-4">
        <select class="modal-select" name="yes-no" disabled>
              ${optionListYesNoNA}
        </select>
      </div>
    `;
      formContent.push(row);
    }
  } else {
    const row = `
    <div class="input-field form-group col-sm-8">
      <select class="modal-select" name="population" disabled>
      <option value>Select a value</option>
        ${optionList}
      </select>
    </div>
    <div class="input-field form-group col-sm-4">
      <select class="modal-select" name="yes-no" disabled>
            ${optionListYesNoNA}
      </select>
    </div>`;
    formContent.push(row);
  }
  $(".population-form").append(
    `<div class="row">
      ${formContent.join("")}
    </div>`
  );
};
