//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: case-notes
//* =======================================

export const caseValues = (list) => {
  const tableBodyContent = [];

  for (const record of list) {
    const {
      ID,
      ContactDate,
      ContactDesc,
      KeyCodeDescription,
      ContactName,
      ContactHours,
      ContactNotes
    } = record;
    const row = `
  <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip" data-placement="left" >
  <td>
  <div class="form-field input-group">
    <input type="text" disabled name="ContactDate" value=${ContactDate}>
  </div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="ContactDesc" value=${ContactDesc}>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="KeyCodeDescription" value=${KeyCodeDescription}>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="ContactName" value=${ContactName}>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="ContactHours" value=${ContactHours}>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="ContactNotes" value=${ContactNotes}>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="Attachment" value='-'>
</div>
</td>
<td>
<div class="form-field input-group">
  <input type="text" disabled name="AttachmentLink" value='-'>
</div>
</td>
  </tr>
`;
    tableBodyContent.push(row);
  }

  return tableBodyContent.join("");
};
