//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: referrals
//* =======================================

// Initializing Luxon DateTime class for the module
const DT = luxon.DateTime;
