//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: History
//* =======================================

import {
  statusList,
  reasonsList,
  centersList,
  createOptionList
} from "../main.js";

// Initializing Luxon DateTime class for the module
const DT = luxon.DateTime;

// Populating the main table
// Data sources:  /data-server/GetHistory
//                /data-server/GetStatusDescSource
//                /data-server/GetGetSepReasons
//                /data-server/GetGEDCenter_TASC
export const tableValues = (list) => {
  // Sorting records in decreasing date of enrollment
  const orderedList = list.sort((record1, record2) =>
    // DT#fromFormat <== Luxon method, "D" token describes mm/dd/yyyy format
    DT.fromFormat(record1.StatusDate, "D") >
    DT.fromFormat(record2.StatusDate, "D")
      ? -1
      : DT.fromFormat(record1.StatusDate, "D") <
        DT.fromFormat(record2.StatusDate, "D")
      ? 1
      : 0
  );
  const tableBodyContent = [];
  for (const record of orderedList) {
    const { ID, StatusDate, StatusID, ExitReasonID, GEDCenterID } = record;
    const optionListStatus = createOptionList(statusList, StatusID);
    const optionListReasons = createOptionList(reasonsList, ExitReasonID);
    const optionListCenters = createOptionList(centersList, GEDCenterID);

    const row = `
    <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip"
    data-placement="left" >
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="StatusDate" value=${StatusDate} >
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="StatusID">
            ${optionListStatus}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="ExitReasonID">
            <option></option>
            ${optionListReasons}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="GEDCenterID">
            <option></option>
            ${optionListCenters}
          </select>
        </div>
      </td>
    </tr>`;

    tableBodyContent.push(row);
  }
  $(".history-table tbody").append(tableBodyContent.join(""));
};

export const addNewRecord = (obj) => {
  const content = [];
  const { labels } = obj;
  let labelClassVal = "";
  let classVal = "";
  for (const keyValue in labels) {
    const labelVal = labels[keyValue];
    let row = "";
    let option = "";
    let value = "";
    // <input> fields
    if (keyValue === "StatusDate") {
      let optionHidden = "form-group";
      const type = keyValue.includes("Date") ? "date" : "text";
      // elementInput() ==> helpers/helperFunctions.js
      row = elementInput({
        keyVal: keyValue,
        labelVal,
        value,
        labelClassVal,
        classVal,
        option,
        optionHidden,
        type
      });
    } else {
      // <select> fields
      let hashTable;
      switch (keyValue) {
        case "StatusID":
          hashTable = statusList;
          break;
        case "ExitReasonID":
          hashTable = reasonsList;
          break;
        case "GEDCenterID":
          hashTable = centersList;
          break;
        default:
          console.log("Default hit - Not right");
          return;
      }
      // elementSelectModal() ==> helpers/helperFunction.js
      row = elementSelectModal({
        hashTable,
        keyValue,
        selectedValue: "",
        labelVal,
        labelClassVal,
        option,
        optionText: ""
      });
    }
    content.push(row);
  }
  console.log("content :>> ", content);
  return content.join("");
};
