//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: best-plus2
//* =======================================

export const createBest2Content = (list) => {
  let content = "";

  return content;
};
