//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: hse
//* =======================================

// Initializing Luxon DateTime class for the module
const DT = luxon.DateTime;

export const createHseContent = (list) => {
  let content = "";
  const fieldList = [];
  const orderedList = list.sort((record1, record2) =>
    // DT#fromFormat <== Luxon method, "D" token describes mm/dd/yyyy format
    DT.fromFormat(record1.TestDate, "D") > DT.fromFormat(record2.TestDate, "D")
      ? -1
      : DT.fromFormat(record1.TestDate, "D") <
        DT.fromFormat(record2.TestDate, "D")
      ? 1
      : 0
  );
  return content;
};
