//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: hse
//* =======================================
import {
  hsePredAct,
  createOptionList,
  createStaffList,
  hseType,
  staffList
} from "../main.js";

// Initializing Luxon DateTime class for the module
const DT = luxon.DateTime;

export const createHseContent = (list) => {
  const tableBodyContent = [];
  const orderedList = list.sort((record1, record2) =>
    // DT#fromFormat <== Luxon method, "D" token describes mm/dd/yyyy format
    DT.fromFormat(record1.TestDate, "D") > DT.fromFormat(record2.TestDate, "D")
      ? -1
      : DT.fromFormat(record1.TestDate, "D") <
        DT.fromFormat(record2.TestDate, "D")
      ? 1
      : 0
  );
  for (const record of orderedList) {
    const {
      ID,
      TestDate,
      TestType,
      TestForm,
      Writing,
      Social,
      Science,
      Reading,
      Math,
      PredAct,
      PreTest,
      Personnel_PKID
    } = record;
    const optionListStaff = createOptionList(
      createStaffList(staffList),
      Personnel_PKID
    );
    const optionListType = createOptionList(hseType, TestType);
    const optionListPredAct = createOptionList(hsePredAct, PredAct);
    const optionListPreTest = createOptionList(
      [
        { key: "0", value: "No" },
        { key: "checked", value: "Yes" }
      ],
      PreTest
    );
    const Score = [Writing, Social, Science, Reading, Math].reduce(
      (result, item) => result + Number(item),
      0
    );
    const row = `
    <tr id=${ID} data-original-title="Click to Edit" data-toggle="tooltip" data-placement="left" >
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="TestDate" value=${TestDate}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="TestType">
            ${optionListType}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="TestForm" value=${TestForm}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Writing" value=${Writing}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Social" value=${Social}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Science" value=${Science}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Reading" value=${Reading}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Math" value=${Math}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <input type="text" disabled name="Score" value=${Score}>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="PredAct">
            ${optionListPredAct}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="PreTest">
            ${optionListPreTest}
          </select>
        </div>
      </td>
      <td>
        <div class="form-group input-field">
          <select class="modal-select" disabled name="Personnel_PKID">
            ${optionListStaff}
          </select>
        </div>
      </td>
    </tr>
  `;
    tableBodyContent.push(row);
  }
  return tableBodyContent.join("");
};
