//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: hse
//* =======================================
import {
  bestPlusForm,
  createOptionList,
  createStaffList,
  staffList
} from "../main.js";

// Initializing Luxon DateTime class for the module
const DT = luxon.DateTime;

export const createHseContent = (list) => {
  const tableBodyContent = [];
  const orderedList = list.sort((record1, record2) =>
    // DT#fromFormat <== Luxon method, "D" token describes mm/dd/yyyy format
    DT.fromFormat(record1.TestDate, "D") > DT.fromFormat(record2.TestDate, "D")
      ? -1
      : DT.fromFormat(record1.TestDate, "D") <
        DT.fromFormat(record2.TestDate, "D")
      ? 1
      : 0
  );
  for (const record of orderedList) {
    const {
      ID,
      TestDate,
      TestType,
      TestForm,
      Writing,
      Social,
      Science,
      Reading,
      Math,
      PredAct,
      PreTest,
      Personnel_PKID
    } = record;
    const optionListStaff = createOptionList(
      createStaffList(staffList),
      Personnel_PKID
    );
    const optionListType = createOptionList();
  }
  return tableBodyContent.join("");
};
