//* Data objects for Funding Reports Page
//*=================================

// For Class Funding Element
const GetFundingSource = [
  {
    FSID: "E",
    FY: "2022",
    FundAbbrev_FY: "E | EPE (2022)",
    FundAbbrev: "E | EPE"
  },
  {
    FSID: "L",
    FY: "2022",
    FundAbbrev_FY: "L | ALE - Adult Literacy Edu (2022)",
    FundAbbrev: "L | ALE - Adult Literacy Edu"
  },
  {
    FSID: "W",
    FY: "2022",
    FundAbbrev_FY: "W | WEP (2022)",
    FundAbbrev: "W | WEP"
  },
  {
    FSID: "Y",
    FY: "2022",
    FundAbbrev_FY: "Y | WIA/WIOA (2022)",
    FundAbbrev: "Y | WIA/WIOA"
  }
];

//For Prepare Report by Element
GetPrepareBy = [
  { key: "0", value: "All " },
  { key: "1", value: "Instructional Offering" },
  { key: "2", value: "Instructional Type" },
  { key: "3", value: "Instructional Format" },
  { key: "4", value: "Instructional Program" },
  { key: "5", value: "Teacher/Tutor" },
  { key: "6", value: "Site" },
  { key: "7", value: "Student Age" },
  { key: "8", value: "Student Employment" }
];

//For Report Criteria Elements

const GetInstructionType = [
  { key: "BE", value: "BE (NRS and/or EPE)" },
  { key: "BN", value: "BENL" },
  { key: "CL", value: "Computer Lab (EPE)" },
  { key: "CLS", value: "Career \u0026 Life Skills (EPE)" },
  { key: "CTS", value: "Citizenship (EPE)" },
  { key: "EB", value: "ESOL-B (NRS)" },
  { key: "ES", value: "ESOL (NRS and/or EPE)" },
  { key: "GE", value: "GED (NRS and/or EPE)" },
  { key: "H", value: "HSE (NRS and/or EPE)" },
  { key: "MA", value: "MATH (NRS and/or EPE)" },
  { key: "NI", value: "Non-Instructional" },
  { key: "O", value: "Other (EPE)" },
  { key: "CM", value: "Case Management" }
];

const GetFormat = [
  { key: "A", value: "CAI Group" },
  { key: "B", value: "Computer Assisted" },
  { key: "C", value: "Class" },
  { key: "G", value: "Small Group" },
  { key: "I", value: "Distance Learning" },
  { key: "L", value: "Lab" },
  { key: "O", value: "Other" },
  { key: "P", value: "Peer Tutoring" },
  { key: "T", value: "Tutorial (One to One)" }
];

const GetSpecialProgramSource = [
  { key: "AI", value: "SMART" },
  { key: "B", value: "Crossroads Café" },
  { key: "D", value: "GRASP" },
  { key: "E", value: "Migrant" },
  { key: "F", value: "Numeracy" },
  { key: "G", value: "EDP" },
  { key: "L", value: "Work Experience" },
  { key: "M", value: "Children/Teens" },
  { key: "P", value: "Parenting/Family Literacy" },
  { key: "Q", value: "Learn to Read" },
  { key: "Z", value: "Workplace Essential Skills" }
];

const GetReportCategory = [
  { key: "16", value: "WIOA Program Evaluation Reports" },
  { key: "196", value: " WIOA Reports" },
  { key: "197", value: "NYRS Program Evaluation Reports" },
  { key: "198", value: "NYRS Reports" },
  { key: "202", value: "WIOA Tables Data Check" },
  { key: "203", value: "WIOA Data Check Reports" },
  { key: "39", value: "EPE Reports" }
];

//For Select Report Element
const GetReport = [
  {
    ID: "208",
    Report_Name:
      "Table 1 Participants by Entering Educational Functioning Level, Ethnicity and Sex",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table1_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "209",
    Report_Name: "Table 2 Participants by Age, Ethnicity and Sex",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table2_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "110",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "237",
    Report_Name: "Table 2A Reportable Individuals by Age, Ethnicity and Sex",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table2A_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "115",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "210",
    Report_Name: "Table 3 Participants by Program Type and Age",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table3_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "120",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "196",
    Report_Name: "Table 4 Measurable Skill Gains by Entry Level",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table4_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "130",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "239",
    Report_Name: "Table 4A - Educational Functioning Level Gain",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table4A_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "132",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "219",
    Report_Name: "Table 4B - Post-tested Participants",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table4B_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "134",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "220",
    Report_Name: "Table 4C - Distance Education",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table4C_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "138",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "201",
    Report_Name: "Table 5 Core Outcome Achievement (Previous FY Exiters)",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table5_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "140",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "221",
    Report_Name: "Table  5A - Distance Education",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table5A_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "144",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "215",
    Report_Name: "Table 6 Participant Status and Program Enrollment",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table6_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "180",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "216",
    Report_Name: "Table 7 Adult Education Personnel by Function and Job Status",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table7_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "200",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "240",
    Report_Name: "Table 9 Outcome Achievement for Participants in IELCE",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table9_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "230",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "227",
    Report_Name:
      "Table 10 Outcome Achievements for Adults in Correctional Education Programs",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table10_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "240",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "241",
    Report_Name:
      "Table 11 Outcome Achievement for Adults in Integrated Education and Training Programs",
    Category_Filter: "196",
    Report_Category: "WIOA Reports",
    FileName: "POP_Reports/table11_wioa.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "260",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "211",
    Report_Name:
      "1 Participants by Entering Educational Functioning Level, Ethnicity and Sex",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck1.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "212",
    Report_Name: "2 Participants by Age, Ethnicity and Sex",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck2.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "110",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "213",
    Report_Name: "3 Participants by Program Type and Age",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck3.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "120",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "235",
    Report_Name: "4 Measurable Skill Gains by Entry Level",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/POPtablesDataCheck4_EFL.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "130",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "222",
    Report_Name: "4B - Post-tested Participants",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/POPtablesDataCheck4B.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "134",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "223",
    Report_Name: "4C - Distance Education",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/POPtablesDataCheck4C.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "138",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "202",
    Report_Name: "5 Core Outcome Achievement (Previous FY Exiters)",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck5.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "140",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "224",
    Report_Name: "5A - Distance Education",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck5A.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "144",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "217",
    Report_Name: "6 Participant Status and Program Enrollment",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck6.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "180",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "218",
    Report_Name: "7 Adult Education Personnel by Function and Job Status",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck7.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "200",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "228",
    Report_Name:
      "10 Education Achievements for Adults in Correctional Education Programs",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/POPtablesDataCheck10_MSG.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "240",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "229",
    Report_Name:
      "10 Outcome Achievements for Adults in Correctional Education Programs",
    Category_Filter: "202",
    Report_Category: "WIOA Tables Data Check",
    FileName: "POP_Reports/WIOA_tablesDataCheck10.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "245",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "12",
    Report_Name: "Students Missing Key Demographics",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "missingKeydemo.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "10",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "190",
    Report_Name: "Students with Invalid Enrollment",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSInvalidStudentEnrollment.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "20",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "9",
    Report_Name: "Students with Invalid Test Scores",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "InvalidTestScores.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "30",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "63",
    Report_Name:
      "Students with Funding Source Not Matching Instruction Funding Source",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSStudentNotMatchingClassFundingSource.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "50",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "13",
    Report_Name: "Student Enrolled Not Counted In NRS",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSInvalidStudentEnrolledNotCounted.aspx",
    Procedure_Name: "ALIESNRS_InvalidStudentEnrolledNotCounted_dwnld",
    Procedure_Param: "1",
    Download_Name: "StudentEnrolledNotCounted.aspx",
    Sort_Order: "90",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "173",
    Report_Name: "Student Assessment and Attendance",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_ParticipantsAssessmentAttendace.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "220",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "174",
    Report_Name:
      "(Download Only) Student Assessment and Attendance w/Instruction Description",
    Category_Filter: "203",
    Report_Category: "NRS Data Check Reports",
    FileName: "NULL",
    Procedure_Name: "WIOA_ParticipantsTableswAssessment_dwnload",
    Procedure_Param: "6",
    Download_Name: "ParticipantsAssessmentAttendance",
    Sort_Order: "230",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "203",
    Report_Name: "Students without Pre-Test",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_NoPreTest.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "204",
    Report_Name: "Students without Post Test",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_NoPostTest.aspx",
    Procedure_Name: "WIOA_InvalidStudentsNoPostTest_dwnload",
    Procedure_Param: "6",
    Download_Name: "StudentNoPostTest",
    Sort_Order: "110",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "205",
    Report_Name: "Students Not Moving to Higher Level",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_NotMovingtoHigher.aspx",
    Procedure_Name: "WIOA_ParticipantsNoProgresswName_dwnld",
    Procedure_Param: "6",
    Download_Name: "StudentNoProgress",
    Sort_Order: "120",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "206",
    Report_Name: "Students Moving to Higher Level",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_MovingtoHigher.aspx",
    Procedure_Name: "WIOA_ParticipantsProgresswName_dwnld",
    Procedure_Param: "6",
    Download_Name: "StudentProgress",
    Sort_Order: "130",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "214",
    Report_Name: "Students Missing Social Security Numbers",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_StudentsMissingSSN.aspx",
    Procedure_Name: "WIOA_ParticipantsTablewName_dwnld",
    Procedure_Param: "6",
    Download_Name: "StudentMissingSSN",
    Sort_Order: "500",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "225",
    Report_Name: "Students with Invalid Social Security Numbers",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_StudentsInvalidSSN.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "550",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "238",
    Report_Name: "Students with Carry Over Hours",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_Students_PFY_HoursLT12.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "600",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "246",
    Report_Name: "Barriers to Employment",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_Reports/WIOA_BarriersEmploy.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "700",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "247",
    Report_Name: "Barriers to Employment Performance Report",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_BarrierEmp_Performance.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "720",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "230",
    Report_Name: "WIOA Outcome Survey Tool",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_Reports/WIOA_OutcomeSurveyTool.aspx",
    Procedure_Name: "WIOA_OutcomeSurveywName_dwnld",
    Procedure_Param: "1",
    Download_Name: "WIOA_OutcomeSurveyTool",
    Sort_Order: "1400",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "193",
    Report_Name: "POP Participants Details and Demographics",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_Reports/POPtablesDataCheck.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1500",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "194",
    Report_Name: "POP MSG Achievement by Name",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_Reports/POPtablesDataCheck4.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1510",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "195",
    Report_Name: "POP MSG Achievement by EFL",
    Category_Filter: "203",
    Report_Category: "WIOA Data Check Reports",
    FileName: "POP_Reports/POPtablesDataCheck4_EFL.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1520",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "16",
    Report_Name: "Program Evaluation Report (NEW)",
    Category_Filter: "16",
    Report_Category: "WIOA Program Evaluation Reports",
    FileName: "POP_Reports/POPProgramEval.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "188",
    Report_Name: "(Download Only) Program Evaluation Report by Class",
    Category_Filter: "16",
    Report_Category: "WIOA Program Evaluation Reports",
    FileName: "NULL",
    Procedure_Name: "WIOA_ProgramEvaluation_Class_dwnld",
    Procedure_Param: "6",
    Download_Name: "ProgramEvaluationbyClass",
    Sort_Order: "500",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "189",
    Report_Name: "(Download Only) Program Evaluation Report by Teacher",
    Category_Filter: "16",
    Report_Category: "WIOA Program Evaluation Reports",
    FileName: "NULL",
    Procedure_Name: "WIOA_ProgramEvaluation_Teacher_dwnld",
    Procedure_Param: "6",
    Download_Name: "ProgramEvaluationbyTeacher",
    Sort_Order: "510",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "12",
    Report_Name: "Students Missing Key Demographics",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "missingKeydemo.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "10",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "190",
    Report_Name: "Students with Invalid Enrollment",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSInvalidStudentEnrollment.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "20",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "9",
    Report_Name: "Students with Invalid Test Scores",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "InvalidTestScores.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "30",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "11",
    Report_Name: "Students without Pre-Test",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NoPreTest.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "40",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "63",
    Report_Name:
      "Students with Funding Source Not Matching Instruction Funding Source",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSStudentNotMatchingClassFundingSource.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "50",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "14",
    Report_Name: "Students Without Post Test",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NoPostTest.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "60",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "13",
    Report_Name: "Student Enrolled Not Counted In NRS",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NRSInvalidStudentEnrolledNotCounted.aspx",
    Procedure_Name: "ALIESNRS_InvalidStudentEnrolledNotCounted_dwnld",
    Procedure_Param: "1",
    Download_Name: "StudentEnrolledNotCounted.aspx",
    Sort_Order: "90",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "173",
    Report_Name: "Student Assessment and Attendance",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "POP_DataCheckReports/WIOA_ParticipantsAssessmentAttendace.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "220",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "174",
    Report_Name:
      "(Download Only) Student Assessment and Attendance w/Instruction Description",
    Category_Filter: "198",
    Report_Category: "NRS Data Check Reports",
    FileName: "NULL",
    Procedure_Name: "WIOA_ParticipantsTableswAssessment_dwnload",
    Procedure_Param: "6",
    Download_Name: "ParticipantsAssessmentAttendance",
    Sort_Order: "230",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "231",
    Report_Name: "ALE Outcome Survey Tool",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "POP_Reports/WIOA_OutcomeSurveyTool.aspx",
    Procedure_Name: "WIOA_OutcomeSurveywName_dwnld",
    Procedure_Param: "1",
    Download_Name: "ALE_OutcomeSurveyTool",
    Sort_Order: "50",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "232",
    Report_Name: "Students Not Moving to Higher Level ",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "NYRS_Reports/NYRSNotMovingtoHigher.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "70",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "233",
    Report_Name: "Students Moving to Higher Level",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "NYRS_Reports/NYRSMovingtoHigher.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "80",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "198",
    Report_Name: "NYRS Participants Details and Demographics",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "NYRS_Reports/NYRStablesDataCheck.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "199",
    Report_Name: "NYRS MSG Achievement by Name",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "NYRS_Reports/NYRStablesDataCheck4.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "500",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "200",
    Report_Name: "NYRS MSG Achievement by EFL",
    Category_Filter: "198",
    Report_Category: "NYRS Reports",
    FileName: "NYRS_Reports/NYRStablesDataCheck4_EFL.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "510",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "197",
    Report_Name: "NYRS Program Evaluation Report",
    Category_Filter: "197",
    Report_Category: "NYRS Program Evaluation Reports",
    FileName: "NYRS_Reports/NYRSProgramEval.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "95",
    Report_Name: "EPE Claim Part 2 160.1 (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClaimPart2_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "96",
    Report_Name: "EPE Claim Part3 160.1 (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClaimPart3_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "2",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "97",
    Report_Name: "Students Included in EPE Reports (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epedatacheck_1601.aspx",
    Procedure_Name: "ALIESEPE_EPEtblDatacheck_Half1_dwnld",
    Procedure_Param: "6",
    Download_Name: "StudentsinEPE_Half1",
    Sort_Order: "3",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "98",
    Report_Name: "Students Included in EPE Reports by Class (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeStudentsIncludedinReports_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "4",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "100",
    Report_Name: "Students Under 21 (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeStudentsUnder21_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "7",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "101",
    Report_Name: "EPE Class Analysis by Age & Hours (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClassAnalysis_1601.aspx",
    Procedure_Name: "ALIESEPE_EPEDataCheckEnrollment_Half1",
    Procedure_Param: "6",
    Download_Name: "EPEClassAnalysis_1601",
    Sort_Order: "8",
    Sort_Order2: "1",
    Filter_Report: "NULL"
  },
  {
    ID: "165",
    Report_Name: "Students Enrolled not Counted (Jul 01 - Dec 31)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeEnrolledNotCounted_1601.aspx",
    Procedure_Name: "ALIESEPE_EPEDataCheckNotCounted_Half1",
    Procedure_Param: "6",
    Download_Name: "EPEEnrolledNotCounted_1601",
    Sort_Order: "100",
    Sort_Order2: "1",
    Filter_Report: "1"
  },
  {
    ID: "135",
    Report_Name: "EPE Claim Part 1 160.2 (Jan 01 - Jun 30) ",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPE_1602_Part1.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "5",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "102",
    Report_Name: "EPE Claim Part 2 160.2 (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClaimPart2_1602.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "10",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "103",
    Report_Name: "EPE Claim Part3 160.2 (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClaimPart3_1602.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "20",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "104",
    Report_Name: "Students Included in EPE Reports (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epedatacheck_1602.aspx",
    Procedure_Name: "ALIESEPE_EPEtblDatacheck_Half2_dwnld",
    Procedure_Param: "6",
    Download_Name: "StudentsinEPE_Half2",
    Sort_Order: "30",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "105",
    Report_Name: "Students Included in EPE Reports by Class (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeStudentsIncludedinReports_1602.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "40",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "107",
    Report_Name: "Students Under 21 (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeStudentsUnder21_1602.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "70",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "108",
    Report_Name: "EPE Class Analysis by Age & Hours (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeClassAnalysis_1602.aspx",
    Procedure_Name: "ALIESEPE_EPEDataCheckEnrollment_Half2",
    Procedure_Param: "6",
    Download_Name: "EPEClassAnalysis_1602",
    Sort_Order: "80",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "136",
    Report_Name: "EPE Amendment Log",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEAmendmentLog.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "90",
    Sort_Order2: "2",
    Filter_Report: "NULL"
  },
  {
    ID: "144",
    Report_Name: "EPE Student Amendment Summary",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentAmendment.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "95",
    Sort_Order2: "2",
    Filter_Report: "1"
  },
  {
    ID: "166",
    Report_Name: "Students Enrolled not Counted (Jan 01 - Jun 30)",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/epeEnrolledNotCounted_1602.aspx",
    Procedure_Name: "ALIESEPE_EPEDataCheckNotCounted_Half2",
    Procedure_Param: "6",
    Download_Name: "EPEEnrolledNotCounted_1602",
    Sort_Order: "100",
    Sort_Order2: "2",
    Filter_Report: "1"
  },
  {
    ID: "134",
    Report_Name: "EPE Students Missing Pre or Post Tests ",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentsNoPrePostTest.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "1",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "109",
    Report_Name: "EPE Monthly Report Part 2",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEClaimMonthlyNoGrad.aspx",
    Procedure_Name: "ALIESEPE_EPEtblClaimReportMonthly_EPENoGrad_dwnld",
    Procedure_Param: "6",
    Download_Name: "EPEMonthlyReport_Part2",
    Sort_Order: "2",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "110",
    Report_Name: "EPE Monthly Report Part 3",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEClaimMonthlyHSGrad.aspx",
    Procedure_Name: "ALIESEPE_EPEtblClaimReportMonthly_EPEHSGrad_dwnld",
    Procedure_Param: "6",
    Download_Name: "EPEMonthlyReport_Part3",
    Sort_Order: "3",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "141",
    Report_Name: "EPE Students not in NRS",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentsNotInNRS.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "3",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "248",
    Report_Name: "EPE 2 Percentage Data Check",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEProgramSummary_EPE2.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "5",
    Sort_Order2: "3",
    Filter_Report: "1"
  },
  {
    ID: "119",
    Report_Name: "EPE HSE Outcome",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentGEDOutcome_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "10",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "120",
    Report_Name: "EPE Non Matching Funding Source",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentNotMatchingClassFundingSource_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "11",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "121",
    Report_Name: "EPE Students Turning 21",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEStudentAge21_1601.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "12",
    Sort_Order2: "3",
    Filter_Report: "NULL"
  },
  {
    ID: "234",
    Report_Name: "EPE Fast Track Performance",
    Category_Filter: "39",
    Report_Category: "EPE Reports",
    FileName: "EPE Reports/EPEFastTrackPerformance.aspx",
    Procedure_Name: "",
    Procedure_Param: "0",
    Download_Name: "",
    Sort_Order: "200",
    Sort_Order2: "3",
    Filter_Report: "1"
  }
];
