//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Public assistance
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data-additional.js/GetPAStatusInfo
//          /original-data/student-data-additional.js/GetPASource
export const assistanceValues = (list, source) => {};
