//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Public assistance
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data-additional.js/GetPAStatusInfo
//          /original-data/student-data-additional.js/GetPASource
export const assistanceValues = (list, source) => {
  // Sorting records from most recent FY to oldest FY
  const orderedList = list.sort((record1, record2) =>
    record1.PAFY > record2.PAFY ? -1 : record1.PAFY < record2.PAFY ? 1 : 0
  );
  const tableBodyContent = [];
  for (const record of orderedList) {
    let { ID, PACatID, PAFY, PACaseNum, PAExhaustTANF } = record;
    const optionList = createOptionList(source, PACatID);
    PAExhaustTANF = PAExhaustTANF ? PAExhaustTANF : "0";
    const optionListYesNo = createOptionList(
      [
        { key: "0", value: "No" },
        { key: "1", value: "Yes" }
      ],
      PAExhaustTANF
    );
    const row = `
    <tr id=${ID}>
      <td>
        <select name="PACatID" disabled>
          ${optionList}
        </select>
      </td>
      <td><input type="text" name="PAFY" value=${PAFY} disabled></td>
      <td><input type="text" name="PACaseNum" value=${PACaseNum} disabled></td>
      <td>
        <select name="PAExhaustTANF" disabled>
          ${optionListYesNo}
        </select>
      </td>
    </tr>`;
    tableBodyContent.push(row);
  }
  $(".population-form tbody").append(tableBodyContent);
};
