//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Employment
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data.js/GetEmploymentInfo
//          /original-data/student-data.js/GetEmploymentStatus
//          /original-data/student-data.js/GetIncome
export const employmentValues = (list, statusList, incomeList) => {};
