//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Employment
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data-additional.js/GetPAStatusInfo
export const employmentValues = (list, source) => {};
