//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Section: Funding sources
//* =======================================

import { createOptionList } from "../main.js";

// Data source: original-data/student-data.js/GetFundingSource
//           original-data/student-data.js/GetFundingInfo
export const fundingValues = (list, sources) => {
  const actualFiscalYear = SESSION_VARIABLE[0].FiscalYear.startsWith(
    "<%= Session"
  )
    ? "2022"
    : SESSION_VARIABLE[0].FiscalYear;

  for (const obj of list) {
    const { FSID, FY } = obj;
    const optionList = createOptionList(sources, FSID);
    const selectFiscalYear = `
    <div class="input-field form-group col-sm-4">
      <select class="modal-select col-sm-4" name="FY">
        <option value=${FY}>${FY}</option>
        <option value=${(Number(FY) - 1).toString()}>${(
      Number(FY) - 1
    ).toString()}</option>
      </select>
    </div>`;

    const selectSource = `
    <div class="input-field form-group col-sm-8">
      <select class="modal-select" name="FSID">
        ${optionList}
      </select>
    </div`;

    $(".funding-form").append(
      `<div class="row">${selectSource}${selectFiscalYear}</div>`
    );
  }
};
