//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Section: Funding sources
//* =======================================

import { createOptionList } from "../main.js";

// Data source: original-data/student-data.js/GetFundingSource
//           original-data/student-data.js/GetFundingInfo
export const fundingValues = (list, sources) => {
  for (const obj of list) {
    const { FSID, FY } = obj;
    const optionList = createOptionList(sources, FSID);
    const FYMinus1 = (Number(FY) - 1).toString();
    const selectFiscalYear = `<div class="input-field form-group col-sm-4"><select class="modal-select" name="FY"><option value=${FY} selected>${FY}</option><option value=${FYMinus1}>${FYMinus1}</option></select></div>`;

    const selectSource = `
    <div class="input-field form-group col-sm-8">
      <select class="modal-select" name=${FSID}>
        ${optionList}
      </select>
    </div>`;

    $(".funding-form").append(
      `<div class="row">
        ${selectSource}
        ${selectFiscalYear}
      </div>`
    );
  }
};
