//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Population categories
//* =======================================

import { createOptionList } from "../main.js";

// Data sources:
export const poulationValues = (obj) => {};
