//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* Sections: Population categories
//* =======================================

import { createOptionList } from "../main.js";

// Data sources: /original-data/student-data-additional.js/GetStudent_Additional
//            /data-server.js/ddlPopulation
export const poulationValues = (obj) => {};
