//* =======================================
//* Populating element values from selected data object
//* generated by first request to server.
//* =======================================

import { dateFormat, createOptionList, createStaffList } from "../main.js";

// Populating input element values
// Data source: original-data/student-data.js/GetStudent
export const inputValues = (list) => {
  $("form input").each(function () {
    const name = $(this).attr("name");
    const value =
      $(this).attr("type") === "date" && name !== "DateSettled"
        ? dateFormat(list[name])
        : list[name];
    $(this).val(value);
  });
};
// Populating Work Eligibility section select values. Adding option list.
// Data source: original-data/student-data.js/GetStudent,
//        data-server.js/GetStaff
export const ssnValues = (list) => {
  $(".ssn-form select[name='NoSSNVisa']").val(list.NoSSNVisa);
  const optionStaff = createOptionList(
    createStaffList(GetStaff),
    list.NoSSNVisaStaff
  );
  $(".ssn-form select[name='NoSSNVisaStaff']").append(optionStaff);
};
