//* Data objects for Students History Page
//*=================================

const GetHistory = [
  {
    ID: "2665637",
    Student_PKID: "1048303",
    StatusDate: "10/31/2019",
    StatusID: "J",
    StatusDesc: "Exit",
    ExitReasonID: "O",
    ExitReason: "Auto Exit Tool",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "2516523",
    Student_PKID: "1048303",
    StatusDate: "07/31/2018",
    StatusID: "J",
    StatusDesc: "Exit",
    ExitReasonID: "O",
    ExitReason: "Auto Exit Tool",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "2182668",
    Student_PKID: "1048303",
    StatusDate: "05/01/2017",
    StatusID: "Z",
    StatusDesc: "Returned After Exit",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "24",
    GEDCenter: "Bronx Adult Learning Center - NYCDOE - 185"
  },
  {
    ID: "2133655",
    Student_PKID: "1048303",
    StatusDate: "01/31/2017",
    StatusID: "J",
    StatusDesc: "Exit",
    ExitReasonID: "O",
    ExitReason: "Auto Exit Tool",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1992479",
    Student_PKID: "1048303",
    StatusDate: "10/12/2016",
    StatusID: "Z",
    StatusDesc: "Returned After Exit",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1966801",
    Student_PKID: "1048303",
    StatusDate: "07/28/2016",
    StatusID: "L",
    StatusDesc: "Inactive",
    ExitReasonID: "K",
    ExitReason: "Entered other education program",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1961724",
    Student_PKID: "1048303",
    StatusDate: "07/01/2016",
    StatusID: "A",
    StatusDesc: "Active",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1951895",
    Student_PKID: "1048303",
    StatusDate: "06/20/2016",
    StatusID: "J",
    StatusDesc: "Exit",
    ExitReasonID: "A",
    ExitReason: "Health problems",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1937684",
    Student_PKID: "1048303",
    StatusDate: "05/14/2016",
    StatusID: "A",
    StatusDesc: "Active",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1808208",
    Student_PKID: "1048303",
    StatusDate: "05/11/2015",
    StatusID: "N",
    StatusDesc: "Referred to TASC",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "208",
    GEDCenter: "Alternative Learning Center - 003"
  },
  {
    ID: "1725817",
    Student_PKID: "1048303",
    StatusDate: "09/16/2014",
    StatusID: "A",
    StatusDesc: "Active",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "",
    GEDCenter: ""
  },
  {
    ID: "1684146",
    Student_PKID: "1048303",
    StatusDate: "06/19/2014",
    StatusID: "A",
    StatusDesc: "Active",
    ExitReasonID: "",
    ExitReason: "",
    GEDCenterID: "",
    GEDCenter: ""
  }
];
const GetStudentHeader = [
  {
    ID: "1048303",
    StudentID: "AA1_JacquesGregoryPRA22620101271987",
    StudentName: "AA1_Jacques, Gregory ",
    BirthDate: "07/12/1987",
    Pop_Order: "",
    POPHours: "",
    POP_Status: "",
    FY_Funding: "Not Enrolled",
    OtherCode: ""
  }
];
const GetStatusDescSource = [
  { key: "A", value: "Active" },
  { key: "G", value: "Assessed \u0026 Referred Elsewhere" },
  { key: "L", value: "Inactive" },
  { key: "M", value: "Left CTEDS" },
  { key: "B", value: "Matched" },
  { key: "O", value: "NRS-Only Exit" },
  { key: "I", value: "On Hold" },
  {
    key: "E",
    value: "Potential (Assessed \u0026 Waiting for Match/Enrollment)"
  },
  { key: "D", value: "Potential (Not Assessed)" },
  { key: "N", value: "Referred to TASC" },
  { key: "Z", value: "Returned After Exit" },
  { key: "K", value: "Unconfirmed Match" },
  { key: "F", value: "Waiting for Rematch/Enrollment" }
];
const GetSepReasons = [
  { key: "A", value: "A Health problems" },
  { key: "B", value: "B Child care problems" },
  { key: "C", value: "C Transportation problems" },
  { key: "D", value: "D Family problems" },
  { key: "E", value: "E Location of class" },
  { key: "F", value: "F Time class scheduled" },
  { key: "G", value: "G Lack of interest" },
  { key: "H", value: "H Changed address/left area" },
  { key: "I", value: "I Got a job" },
  { key: "J", value: "J Entered training program" },
  { key: "K", value: "K Entered other education program" },
  { key: "L", value: "L Other reason" },
  { key: "M", value: "M Unknown reason" },
  { key: "N", value: "N Never in class" },
  { key: "O", value: "O Auto Exit Tool" },
  { key: "P", value: "P Completed objectives" },
  { key: "Q", value: "Q Tutor Termination" },
  { key: "R", value: "R Lack of Available Tutors" },
  { key: "S", value: "S Instruction not Relevant" },
  { key: "Y", value: "Y Released from Institution" },
  { key: "Z", value: "Z Deceased" }
];
const GetGEDCenter_TASC = [
  { key: "1", value: "Adirondack Correctional Facility - NYSDOCCS - 921" },
  { key: "2", value: "Adirondack Educational Center - 393" },
  { key: "106", value: "Adult Learning Center - 160" },
  { key: "3", value: "Akwasasne Boys and Girls Club - 460" },
  { key: "4", value: "Albany County Correctional Facility - 702" },
  { key: "5", value: "Albion Correctional Facility - NYSDOCCS - 704" },
  { key: "6", value: "Allegany County Jail - 734" },
  { key: "208", value: "Alternative Learning Center - 003" },
  { key: "8", value: "Altona Correctional Facility - NYSDOCCS - 711" },
  { key: "81", value: "Angola-Carrier Educational Center - 004" },
  { key: "107", value: "Arcadia Middle School - Greece CSD - 305" },
  { key: "82", value: "Ashville-Hewes Educational Center - 005" },
  { key: "12", value: "Attica Correctional Facility - NYSDOCCS - 714" },
  { key: "13", value: "Auburn Correctional Facility - NYSDOCCS - 716" },
  { key: "15", value: "Bare Hill Correctional Facility - NYSDOCCS - 867" },
  { key: "19", value: "Bedford Hills Correctional Facility - NYSDOCCS - 731" },
  { key: "20", value: "Berkshire Jr.-Sr. High School - 533" },
  { key: "21", value: "Best Resource Center, Inc. - 072" },
  { key: "22", value: "Biondi Educational Center - 620" },
  { key: "310", value: "Biondi Elementary School - 622" },
  { key: "295", value: "Boys and Girls High School - NYCDOE - 077" },
  { key: "23", value: "Brentwood Residential Center - NYSOCFS - 784" },
  { key: "24", value: "Bronx Adult Learning Center - NYCDOE - 185" },
  { key: "26", value: "Bronx Psychiatric Rehab Center - 523" },
  { key: "302", value: "Bronx Regional High School Hub - NYCDOE - 186" },
  { key: "57", value: "Bronx Works-Morris Senior Center - 051" },
  { key: "27", value: "Brooklyn Adult Learning Center NYCDOE - 063" },
  { key: "28", value: "Brooklyn College Adult Literacy - 055" },
  { key: "29", value: "Brooklyn Educational Opportunity Center - SUNY - 066" },
  { key: "32", value: "Brookwood Secure Center - NYSOCFS - 770" },
  { key: "33", value: "Broome County Correctional Facility - 736" },
  { key: "34", value: "Broome-Tioga BOCES-Johnson City Learning Center - 130" },
  { key: "35", value: "Buffalo Adult Learning Center - 068" },
  { key: "36", value: "Buffalo Educational Opportunity Center - SUNY - 070" },
  { key: "39", value: "Cape Vincent Correctional Facility - NYSDOCCS - 762" },
  {
    key: "315",
    value: "Capital District Educational Opportunity Center - 170"
  },
  { key: "40", value: "CASES - 465" },
  { key: "41", value: "Cassadaga Job Corps Center - 494" },
  { key: "42", value: "Cattaraugus County Jail - 855" },
  { key: "44", value: "Cattaraugus-Allegany BOCES-Center at Olean - 325" },
  {
    key: "45",
    value: "Cattaraugus-Allegany- Erie BOCES-Center at Belmont - 030"
  },
  {
    key: "43",
    value: "Cattaraugus-Allegany-BOCES Center at Ellicottville - 115"
  },
  { key: "46", value: "Cayuga Correctional Facility - NYSDOCCS - 884" },
  { key: "47", value: "Cayuga County Public Safety Bldg. - 717" },
  { key: "48", value: "Cayuga-Onondaga - BOCES - 011" },
  { key: "50", value: "Central New York Psychiatric Center - 670" },
  { key: "51", value: "Champlain Valley Educational Services - 346" },
  { key: "53", value: "Chautauqua County Jail - 877" },
  { key: "54", value: "Chelsea Recreation Center - 493" },
  { key: "55", value: "Chemung County Jail - 804" },
  { key: "56", value: "Chenango County Jail - 898" },
  { key: "317", value: "Christ Community Church - 164" },
  { key: "316", value: "City College - 128" },
  { key: "58", value: "Clinton Correctional Facility Main - NYDOCCS - 783" },
  { key: "59", value: "Clinton County Jail - 917" },
  {
    key: "60",
    value: "Clinton-Essex BOCES-Champlain Valley Ed. Services - 266"
  },
  { key: "61", value: "Collins Correctional Facility - NYSDOCCS - 827" },
  { key: "62", value: "Columbia County Jail - 834" },
  { key: "63", value: "Cortland County Jail - 777" },
  { key: "64", value: "Coxsackie Correctional Facility - NYSDOCCS - 989" },
  { key: "65", value: "CPSU/OBCC (CENTRAL PUNITIVE SEG UNIT) - 805" },
  { key: "66", value: "Creedmoor Psychiatric Center, Educ. Dept. - 578" },
  { key: "67", value: "Daytop Village Inc., Swan Lake - 653" },
  { key: "70", value: "Delaware County Jail - 785" },
  { key: "69", value: "Delaware Valley Job Corps Center - 495" },
  { key: "71", value: "Downstate Correctional Facility - NYSDOCCS - 809" },
  { key: "30", value: "Downtown Brooklyn ACCESS - NYCDOE - 297" },
  { key: "72", value: "Dunkirk Senior High School - 102" },
  { key: "73", value: "Dutchess Community College - 356" },
  { key: "74", value: "Dutchess County Jail - 919" },
  { key: "75", value: "East Meadow Public School Annex - 799" },
  { key: "76", value: "Eastern New York Correctional Facility NYSDOCCS - 887" },
  {
    key: "77",
    value: "Eastern Suffolk BOCES-Brookhaven Technical Center - 029"
  },
  {
    key: "78",
    value: "Eastern Suffolk BOCES-H. B. Ward Technical Center - 463"
  },
  { key: "79", value: "Elmira Correctional Facility - NYSDOCCS - 803" },
  { key: "221", value: "ERA@Robert N. Davoren(RNDC) - 792" },
  {
    key: "80",
    value: "Eric M. Taylor Ctr. (EMTC) RIDE @ East River Acad. - 802"
  },
  { key: "319", value: "ERIE CC North Campus - 071" },
  { key: "83", value: "Erie Community College South - 104" },
  { key: "84", value: "Erie County Correctional Facility - 708" },
  { key: "85", value: "Erie County Holding Center - 755" },
  { key: "312", value: "Essex County Correctional Facility - 840" },
  { key: "86", value: "FEGS/Begin - 510" },
  { key: "313", value: "Finger Lakes Community College - Canandaigua - 142" },
  { key: "318", value: "Finger Lakes Community College - Geneva - 146" },
  { key: "314", value: "Finger Lakes Community College - Newark - 143" },
  { key: "87", value: "Finger Lakes Residential Center - NYSOCFS - 854" },
  { key: "88", value: "Fishkill Correctional Facility - NYSDOCCS - 726" },
  { key: "89", value: "Five Points Correctional Facility - NYSDOCCS - 937" },
  { key: "91", value: "Franklin Correctional Facility - NYSDOCCS - 869" },
  { key: "92", value: "Franklin County Jail - 868" },
  { key: "93", value: "Franklin Essex Hamilton BOCES - 254" },
  { key: "95", value: "Fulton County Correctional Facility - 846" },
  { key: "96", value: "Genesee County Jail - 721" },
  { key: "97", value: "Genesee Valley BOCES(Mt. Morris/Batavia ) - 270" },
  { key: "98", value: "Geneva Middle School - 145" },
  {
    key: "99",
    value: "George Montchan Detention Ctr. (GMDC) @ East River - 786"
  },
  {
    key: "100",
    value: "George R. Vierno Ctr. (GRVC) @ East River Academy - 787"
  },
  { key: "101", value: "Glenmont Job Corps Center - 499" },
  { key: "102", value: "Goshen Residential Center - NYSOCFS - 820" },
  { key: "103", value: "Gouverneur Correctional Facility - NYSDOCCS - 823" },
  { key: "104", value: "Gowanda Correctional Facility - NYSDOCCS - 824" },
  { key: "105", value: "Great Meadow Correctional Facility - NYSDOCCS - 772" },
  { key: "108", value: "Green Haven Correctional Facility - NYSDOCCS - 956" },
  { key: "109", value: "Greene Correctional Facility- NYSDOCCS - 779" },
  { key: "111", value: "Groveland Correctional Facility-NYSDOCCS - 945" },
  { key: "112", value: "GST BOCES - 120" },
  { key: "320", value: "GST BOCES - Landon Plaza - 409" },
  { key: "113", value: "Hale Creek ASACTC - NYSDOCCS - 843" },
  { key: "114", value: "Hamilton-Fulton-Montgomery BOCES - 223" },
  { key: "115", value: "HANAC - 279" },
  { key: "117", value: "Haverling High School - 408" },
  { key: "118", value: "Hawthorne Cedar Knolls USFD - 573" },
  { key: "119", value: "Herkimer County Community College - 446" },
  { key: "121", value: "Highland Residential Center - NYSOCFS - 832" },
  { key: "240", value: "Holy Trinity Roman Catholic Church - 036" },
  { key: "123", value: "Hudson Correctional Facility - NYSDOCCS - 835" },
  { key: "124", value: "Industry School - NYSOCFS - 837" },
  { key: "125", value: "Ives School-Lincoln Hall - 593" },
  { key: "306", value: "Jamaica Hub - NYCDOE - 374" },
  { key: "303", value: "Jamestown CSD-Technical Academy - 201" },
  { key: "126", value: "Jefferson County Correctional Facility - 983" },
  { key: "127", value: "Jefferson-Lewis BOCES BOHLEN Technical Center - 457" },
  { key: "128", value: "Jewish Guild for the Blind - 605" },
  { key: "296", value: "JOHNSON VOCATIONAL CENTER - 078" },
  { key: "130", value: "Kenmore Town of Tonawanda (ECC North Campus) - 069" },
  { key: "132", value: "Kingsborough Community College-CUNY - 064" },
  { key: "133", value: "Kingston High School - 225" },
  { key: "134", value: "Kirby Forensic Psychiatric Center - 678" },
  { key: "135", value: "LaGuardia Community College CUNY - 248" },
  {
    key: "136",
    value: "Lakeview Shock Incarceration Corr. Fac. - NYSDOCCS - 739"
  },
  {
    key: "139",
    value: "Lehman College, Office of Cont. Education - CUNY - 052"
  },
  { key: "140", value: "Lewis County Jail - 861" },
  { key: "141", value: "Livingston Correctional Facility - NYSDOCCS - 947" },
  { key: "142", value: "Livingston County Jail - 816" },
  { key: "144", value: "Long Beach Adult Learning Center - 056" },
  {
    key: "297",
    value: "Long Island Educational Opportunity Center (CBT) - 144"
  },
  { key: "147", value: "MacCormick Secure Center - NYSOCFS - 753" },
  { key: "148", value: "Madison County Jail c/oPublic Safety Building - 973" },
  { key: "150", value: "Madison-Oneida BOCES - 445" },
  { key: "304", value: "Manhattan Hub - NYCDOE - 261" },
  { key: "152", value: "Manhattan Psychiatric Center - 610" },
  { key: "305", value: "Marcy Avenue Complex Hub - NYCDOE - 293" },
  { key: "154", value: "Marcy Correctional Facility - NYSDOCCS - 871" },
  {
    key: "156",
    value: "Maryvale CSD-Maryvale Community Education Building - 256"
  },
  { key: "157", value: "Medgar Evers College - 450" },
  { key: "160", value: "Mid-Manhattan Adult Learning Center - NYCDOE - 291" },
  { key: "162", value: "Mid-State Correctional Facility - NYSDOCCS - 873" },
  { key: "158", value: "Middletown CSD- Middletown High School - 265" },
  { key: "163", value: "Mitchel Community Center - Eastside House - 250" },
  { key: "164", value: "Mohawk Correctional Facility - NYSDOCCS - 936" },
  {
    key: "301",
    value: "Mohawk Valley CC Assessment and Testing Cntr.(CBT) - 176"
  },
  { key: "165", value: "Monroe 1 BOCES - 133" },
  { key: "299", value: "Monroe 2 BOCES (CBT) - 172" },
  { key: "300", value: "Monroe 2 BOCES (CBT) - 173" },
  { key: "166", value: "Monroe County Correctional Facility - 932" },
  { key: "167", value: "Monroe County Jail - 931" },
  { key: "168", value: "Mont Pleasant Middle School - 397" },
  { key: "170", value: "Montgomery County Correctional Facility - 812" },
  {
    key: "171",
    value: "Moriah Shock Incarceration Corr. Fac. - NYSDOCCS - 879 "
  },
  { key: "181", value: "Mosholu Montefiore Community Center - 006" },
  { key: "173", value: "Mt. Pleasant Blythedale UFSD - 385" },
  { key: "174", value: "Nassau BOCES- Technical Center - 075" },
  { key: "175", value: "Nassau Community College - 141" },
  { key: "176", value: "New Dorp High School - NYCDOE - 412" },
  { key: "177", value: "Niagara County Jail - 857" },
  { key: "178", value: "Niagara Falls Community Education Center - 298" },
  { key: "180", value: "North Rockland High School - 420" },
  { key: "182", value: "Norwich City High School - 313" },
  { key: "184", value: "OCM BOCES Career Training Center - 241" },
  { key: "183", value: "OCM BOCES- Center for New Careers - 081" },
  { key: "185", value: "Odyssey House Inc. - 613" },
  { key: "186", value: "Ogdensburg Correctional Facility NYSDOCCS - 901" },
  { key: "188", value: "Oneida Access Site - 150" },
  { key: "190", value: "Oneida County Jail - 903" },
  { key: "192", value: "Oneonta Adult Education - 330" },
  { key: "191", value: "Oneonta Job Corps Center - 496" },
  { key: "193", value: "Onondaga County Department of Corrections - 841" },
  {
    key: "194",
    value: "Onondaga County Sheriff\u0027s Dept, Justice Center - 960"
  },
  {
    key: "195",
    value: "Onondaga County Sheriff\u0027s Office Community Site - 961"
  },
  { key: "196", value: "Ontario County Jail - 758" },
  { key: "197", value: "Orange County Community College - 076" },
  { key: "198", value: "Orange County Correctional Facility - 821" },
  { key: "199", value: "Orange-Ulster BOCES - 239" },
  { key: "200", value: "Orleans Correctional Facility - NYSDOCCS - 706" },
  { key: "201", value: "Orleans County Jail - 705" },
  { key: "202", value: "Oswego County BOCES@CCC - 263" },
  {
    key: "204",
    value: "Otis Bantrum Corr. Ctr.(OBCC) @ East River Academy - 797"
  },
  { key: "205", value: "Otisville Correctional Facility - NYSDOCCS - 909" },
  { key: "206", value: "Otsego County Correctional Facility - 775" },
  { key: "209", value: "Phoenix Academy HS - 560" },
  { key: "210", value: "Phoenix House, Belle Terre Facility - 949" },
  { key: "211", value: "Pilgrim Psychiatric Center - 683" },
  { key: "212", value: "Putnam County Correctional Facility - 764" },
  { key: "213", value: "Putnam-Northern Westchester - BOCES - 491" },
  { key: "307", value: "Queens Adult Learning Center - NYCDOE - 378" },
  { key: "214", value: "Queens Educational Opportunity Center - SUNY - 375" },
  { key: "308", value: "Queens Library - 379" },
  { key: "294", value: "Questar III - Rensselaer Educational Center - 181" },
  {
    key: "215",
    value: "Questar III- Columbia-Greene Educational Center - 180"
  },
  { key: "216", value: "Red Hook Residential Center - NYSOCFS - 926" },
  { key: "218", value: "Renaissance Addiction Services Inc. - 689" },
  { key: "219", value: "Rensselaer County Jail - 964" },
  { key: "220", value: "Riverview Correctional Facility - NYSDOCCS - 900" },
  { key: "222", value: "Rochester CSD-Family Learning Center - 377" },
  {
    key: "223",
    value: "Rochester Educational Opportunity Center - SUNY - 380"
  },
  { key: "224", value: "Rockland County Jail - 889" },
  { key: "225", value: "Rome Access Site - 175" },
  { key: "226", value: "Rose M. Singer Ctr.(RMSC) @ East River Academy - 796" },
  { key: "260", value: "Samaritan Village Cape Road - 600" },
  { key: "227", value: "Samaritan Village Inc. - 553" },
  { key: "228", value: "Saratoga County Correctional Facility - 719" },
  { key: "229", value: "Schenectady County Community College - 398" },
  { key: "230", value: "Schenectady County Correctional Facility - 940" },
  { key: "232", value: "Schuyler County Jail - 972" },
  { key: "233", value: "Seneca County Jail - 980" },
  {
    key: "234",
    value: "Sgt Henry Johnson Youth Leadership Academy-NYSOCFS - 948"
  },
  { key: "235", value: "Shawangunk Correctional Facility - NYSDOCCS - 970" },
  { key: "236", value: "Sing Sing Correctional Facility - NYSDOCCS - 905" },
  {
    key: "237",
    value: "Southern NY Resid. Ctr, Bronx Resid Cntr - NYSOCFS - 741"
  },
  { key: "238", value: "Southport Correctional Facility - NYSDOCCS - 906" },
  { key: "239", value: "St. Demetrios H.S. of Astoria - 570" },
  {
    key: "241",
    value: "St. Lawrence-Lewis BOCES- Seaway Area Tech Center - 320"
  },
  { key: "242", value: "St.Lawrence-Lewis Correctional Facility - 760" },
  { key: "244", value: "Steuben County Jail - 723" },
  { key: "245", value: "Suffolk CCC - Riverhead Campus - 415" },
  { key: "247", value: "Suffolk County Comm College - Brentwood Campus - 413" },
  { key: "246", value: "Suffolk County Community College - 411" },
  { key: "249", value: "Suffolk County Correctional Facility - Min - 998" },
  { key: "248", value: "Suffolk County Correctional Facility Max - 929" },
  { key: "250", value: "Suffolk County Day Reporting Center - 910" },
  { key: "251", value: "Sullivan Correctional Facility - NYSDOCCS - 807" },
  { key: "252", value: "Sullivan County BOCES - 240" },
  { key: "253", value: "Sullivan County Jail - 882" },
  { key: "151", value: "SUNY - Manhattan EOC - 255" },
  { key: "298", value: "Syracuse City School District (CBT) - 165" },
  { key: "255", value: "Syracuse Educational Opportunity Ctr.- SUNY - 417" },
  { key: "256", value: "Taberg Residential Center - NYSOCFS - 963" },
  { key: "257", value: "Taconic Correctional Facility - NYSDOCCS - 732" },
  { key: "311", value: "The Catholic Guild for the Blind - 646" },
  { key: "258", value: "The College of Staten Island - 067" },
  { key: "261", value: "Tioga County Jail - 911" },
  { key: "262", value: "Tompkins County Jail - Public Safety Bldg. - 839" },
  { key: "263", value: "Tompkins-Seneca-Tioga BOCES - 194" },
  { key: "264", value: "Trott Access Center - 035" },
  { key: "267", value: "Turning Point Ed. Center - 635" },
  { key: "268", value: "Ulster Correctional Facility - NYSDOCCS - 780" },
  { key: "269", value: "Ulster County Jail - 849" },
  { key: "270", value: "Upstate Correctional Facility - NYSDOCCS - 870" },
  { key: "272", value: "Wallkill Correctional Facility - NYSDOCCS - 971" },
  { key: "273", value: "Warren County Jail - 851" },
  { key: "274", value: "Washington Correctional Facility - NYSDOCCS - 773" },
  { key: "275", value: "Washington County Jail - 938" },
  { key: "309", value: "Washington Irving Educational Center - 395" },
  { key: "276", value: "Watertown Correctional Facility - NYSDOCCS - 982" },
  { key: "277", value: "Wayne County Correctional Facility - 865" },
  { key: "278", value: "Wayne Finger Lakes BOCES - 273" },
  { key: "279", value: "Wende Correctional Facility - NYSDOCCS - 709" },
  { key: "281", value: "Westchester County Jail - Men - 966" },
  { key: "282", value: "Westchester EOC - 050" },
  { key: "283", value: "White Plains CSD - Rochambeau School - 475" },
  { key: "284", value: "Willard Drug Treatment Campus - NYSDOCCS - 692" },
  { key: "286", value: "Woodbourne Correctional Facility - NYSDOCCS - 996" },
  { key: "288", value: "WSWHE BOCES - 155" },
  { key: "289", value: "WSWHE- BOCES- Adult Learning Center - 394" },
  { key: "290", value: "Wyoming Correctional Facility - NYSDOCCS - 713" },
  { key: "291", value: "Wyoming County Jail - 975" },
  { key: "292", value: "Yates County Jail - 913" },
  { key: "293", value: "Yonkers CSD/VIVE SCHOOL/ Pathways to Success - 487" }
];
